/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatSessionKeyRouteImport } from './routes/chat/$sessionKey'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiPathsRouteImport } from './routes/api/paths'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiAuthUnlockRouteImport } from './routes/api/auth/unlock'
import { Route as ApiAuthLockRouteImport } from './routes/api/auth/lock'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionKeyRoute = ChatSessionKeyRouteImport.update({
  id: '/chat/$sessionKey',
  path: '/chat/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPathsRoute = ApiPathsRouteImport.update({
  id: '/api/paths',
  path: '/api/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUnlockRoute = ApiAuthUnlockRouteImport.update({
  id: '/api/auth/unlock',
  path: '/api/auth/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLockRoute = ApiAuthLockRouteImport.update({
  id: '/api/auth/lock',
  path: '/api/auth/lock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/new': typeof NewRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/api/auth/lock': typeof ApiAuthLockRoute
  '/api/auth/unlock': typeof ApiAuthUnlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/new': typeof NewRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/api/auth/lock': typeof ApiAuthLockRoute
  '/api/auth/unlock': typeof ApiAuthUnlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/new': typeof NewRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/api/auth/lock': typeof ApiAuthLockRoute
  '/api/auth/unlock': typeof ApiAuthUnlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/new'
    | '/api/history'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/sessions'
    | '/api/stream'
    | '/chat/$sessionKey'
    | '/api/auth/lock'
    | '/api/auth/unlock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/new'
    | '/api/history'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/sessions'
    | '/api/stream'
    | '/chat/$sessionKey'
    | '/api/auth/lock'
    | '/api/auth/unlock'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/new'
    | '/api/history'
    | '/api/paths'
    | '/api/ping'
    | '/api/send'
    | '/api/sessions'
    | '/api/stream'
    | '/chat/$sessionKey'
    | '/api/auth/lock'
    | '/api/auth/unlock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  NewRoute: typeof NewRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiPathsRoute: typeof ApiPathsRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ChatSessionKeyRoute: typeof ChatSessionKeyRoute
  ApiAuthLockRoute: typeof ApiAuthLockRoute
  ApiAuthUnlockRoute: typeof ApiAuthUnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionKey': {
      id: '/chat/$sessionKey'
      path: '/chat/$sessionKey'
      fullPath: '/chat/$sessionKey'
      preLoaderRoute: typeof ChatSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paths': {
      id: '/api/paths'
      path: '/api/paths'
      fullPath: '/api/paths'
      preLoaderRoute: typeof ApiPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/unlock': {
      id: '/api/auth/unlock'
      path: '/api/auth/unlock'
      fullPath: '/api/auth/unlock'
      preLoaderRoute: typeof ApiAuthUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/lock': {
      id: '/api/auth/lock'
      path: '/api/auth/lock'
      fullPath: '/api/auth/lock'
      preLoaderRoute: typeof ApiAuthLockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  NewRoute: NewRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiPathsRoute: ApiPathsRoute,
  ApiPingRoute: ApiPingRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiStreamRoute: ApiStreamRoute,
  ChatSessionKeyRoute: ChatSessionKeyRoute,
  ApiAuthLockRoute: ApiAuthLockRoute,
  ApiAuthUnlockRoute: ApiAuthUnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
